Enhanced all the scripts: Fail on first error, all scripts can be called from any folder, and scripts are parameterized when needed.

diff --git a/installation/install_tar b/installation/install_tar
--- a/installation/install_tar
+++ b/installation/install_tar
@@ -3,9 +3,24 @@
 # files that were created in the process. This file is
 # used when uninstalling the tarball again using
 # uninstall_tar.
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
-cd $DIR/..
-tar xzf map-*.tar.gz
-cd map-*
-sudo python setup.py install --record $DIR/installed_files.txt
-cd ..
+# install_tar requires one parameter, which is the
+# version number to be installed.
+
+# Fail on first error:
+set -e
+
+if [[ $# -eq 1 ]]
+then
+	OLD_DIR=$(pwd)
+	DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
+	cd $DIR
+	tar xzf map-$1.tar.gz
+	cd map-$1
+	sudo python setup.py install --record $DIR/installed_files.txt
+	cd ..
+	sudo rm -r map-$1	
+	cd $OLD_DIR
+else
+	echo "Usage: install_tar [version number]"
+	echo "Example: install_tar 1.2.0"
+fi
diff --git a/scripts/build_signed_deb b/scripts/build_signed_deb
--- a/scripts/build_signed_deb
+++ b/scripts/build_signed_deb
@@ -2,31 +2,47 @@
 # *** Build Signed deb Package *** 
 # ********************************
 
-# Since stdeb cannot sign packages itself, we must unpack 
-# in a temporary folder 'signed_deb':
+# The required parameter is the targeted version number:
 
-mkdir signed_deb 
-cd signed_deb
+# Fail on first error:
+set -e
 
-# Unpack the sources and navigate to the unpacked folder:
+if [[ $# -eq 1 ]]
+then
+	# First, we move to the right directory:
+	OLD_DIR=$(pwd)
+	DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
+	cd $DIR/..
+ 
+	# Since stdeb cannot sign packages itself, we must unpack 
+	# in a temporary folder 'signed_deb':
 
-dpkg-source -x ../deb_dist/map_1.1.0-1.dsc
-cd map-1.1.0
+	mkdir signed_deb 
+	cd signed_deb
 
-# Copy over the license file because debian requires it:
-cp ../../LICENSE debian/copyright
+	# Unpack the sources and navigate to the unpacked folder:
 
-# Change the version to a Ubuntu compatible version:
-sed -i '0,/-1/s//-0ubuntu1/' debian/changelog 
+	dpkg-source -x ../deb_dist/map_$1-1.dsc
+	cd map-$1
 
-# Change the name of the binary from python-map to map:
-sed -i 's/python-map/map/g' debian/control
+	# Copy over the license file because debian requires it:
+	cp ../../LICENSE debian/copyright
 
-# Change the version to the latest to remove the lintian warning:
-sed -i '/Standards-Version/c\Standards-Version: 3.9.3' debian/control
+	# Change the version to a Ubuntu compatible version:
+	sed -i '0,/-1/s//-0ubuntu1/' debian/changelog 
 
-# Build the new signed package:
-debuild -S -sa
+	# Change the name of the binary from python-map to map:
+	sed -i 's/python-map/map/g' debian/control
 
-# Navigate back to the original folder:
-cd ../..
+	# Change the version to the latest to remove the lintian warning:
+	sed -i '/Standards-Version/c\Standards-Version: 3.9.3' debian/control
+
+	# Build the new signed package:
+	debuild -S -sa
+
+	# Navigate back to the original folder:
+	cd $OLD_DIR
+else
+        echo "Usage: build_signed_deb [version number]"
+        echo "Example: build_signed_deb 1.2.0"
+fi
diff --git a/scripts/submit_to_launchpad b/scripts/submit_to_launchpad
--- a/scripts/submit_to_launchpad
+++ b/scripts/submit_to_launchpad
@@ -2,11 +2,24 @@
 # *** Submit to Launchpad  *** 
 # ****************************
 
-# Move to the signed_deb folder:
-cd signed_deb
+# The required parameter is the targeted version number:
 
-# Upload the package to Launchpad to the provided PPA:
-dput ppa:thamasta/thlo-utils map_1.1.0-0ubuntu1_source.changes
+# Fail on first error:
+set -e
 
-# Navigate back to the original folder:
-cd ../..
+if [[ $# -eq 1 ]]
+then
+	# First, we move to the right directory:
+    OLD_DIR=$(pwd)
+    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
+	cd $DIR/signed_deb
+
+	# Upload the package to Launchpad to the provided PPA:
+	dput ppa:thamasta/thlo-utils map_$1-0ubuntu1_source.changes
+
+	# Navigate back to the original folder:
+	cd $OLD_DIR
+else
+        echo "Usage: submit_to_launchpad [version number]"
+        echo "Example: submit_to_launchpad 1.2.0"
+fi
diff --git a/scripts/submit_to_pypi b/scripts/submit_to_pypi
--- a/scripts/submit_to_pypi
+++ b/scripts/submit_to_pypi
@@ -2,9 +2,15 @@
 # *** Submit to PyPI *** 
 # **********************
 
+# Fail on first error:
+set -e
+
+# Get the directory where this script is stored:
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
+
 # Register map against PyPI's server:
 echo "Registering map..."
-python setup.py register -r pypi
+python $DIR/../setup.py register -r pypi
 
 # Wait a moment:
 echo "Waiting a moment before uploading..."
@@ -12,5 +18,5 @@ sleep(10)
 
 # Upload map to PyPI's server: 
 echo "Uploading map..."
-python setup.py sdist upload -r pypi
+python $DIR/../setup.py sdist upload -r pypi
 echo "Done."
diff --git a/scripts/submit_to_pypitest b/scripts/submit_to_pypitest
--- a/scripts/submit_to_pypitest
+++ b/scripts/submit_to_pypitest
@@ -2,9 +2,15 @@
 # *** Submit to PyPI Test *** 
 # ***************************
 
+# Fail on first error:
+set -e
+
+# Get the directory where this script is stored:
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
+
 # Register map against PyPI's test server:
 echo "Registering map..."
-python setup.py register -r pypitest
+python $DIR/../setup.py register -r pypitest
 
 # Wait a moment:
 echo "Waiting a moment before uploading..."
@@ -12,5 +18,5 @@ sleep(10)
 
 # Upload map to PyPI's test server: 
 echo "Uploading map..."
-python setup.py sdist upload -r pypitest
+python $DIR/../setup.py sdist upload -r pypitest
 echo "Done."
